---
SPD_HOME_DIR_CONTENT: "custom/tars/home_{{ SPD_UNAME }}.tgz"
SPD_UNAME: "{{ SPD_REAL_UNAME }}"
SPD_REAL_UNAME: hepp

SPD_NO_BLANKS:
  - bash # The GNU Bourne Again shell
  - bash-completion # Command-line tab-completion for bash

#
#  Support for man pages
#
SPD_APK_MAN: # will be installed if SPD_PKGS_MAN=1
  - docs
  - hepp

SPD_WITH_BLANKS:
  - bash # The GNU Bourne Again shell
  - bash-completion # Command-line tab-completion for bash

  - zsh

SPD_EMPTY:
SPD_EMPTY_NOT: alpha

SPD_CONTENT: something
SPD_REF_1: "{{ SPD_CONTENT }}"
SPD_REF_2: "{{ SPD_REF_4 }}"
SPD_REF_3: "{{ SPD_REF_2 }}"
SPD_REF_4: "{{ SPD_REF_3 }}"
SPD_REF_5: "{{ SPD_REF_4 }}"
