#!/bin/sh
#
# Copyright (c) 2021-2024: Jacob.Lundqvist@gmail.com
# License: MIT
#
# Part of https://github.com/jaclu/helpful-scripts
#
#  Updates apk status of an Alpine based box
#

display_time_elapsed() {
    dte_label="$1"
    dte_duration=$(($(date +%s) - t_start))

    if [ "$dte_duration" -gt 59 ]; then
        dte_hours=$((dte_duration / 3600))
        dte_minutes=$(((dte_duration % 3600) / 60))
        dte_seconds=$((dte_duration - dte_hours * 3600 - dte_minutes * 60))
        dte_elapsed=$(printf '%02d:%02d:%02d' "$dte_hours" "$dte_minutes" "$dte_seconds")
    else
        dte_elapsed=$(printf '%ss' "$dte_duration")
    fi
    echo
    printf 'Time elapsed: %s - %s\n' "$dte_elapsed" "$dte_label"
    echo
}

#===============================================================
#
#   Main
#
#===============================================================

prog_name=$(basename "$0")
if [ "$(whoami)" != "root" ]; then
    echo "Executing $prog_name as root"

    #  Providing some env variables that are needed to be kept in the sudo
    sudo "$0" "$@"
    exit_code="$?"

    #  terminate the user initiated instance of the script
    exit "$exit_code"
fi

t_start="$(date +%s)"

echo "===  Mapk - apk maintenance  ==="

if ! apk fix || ! apk upgrade; then
    echo "ERROR detected by Mapk"
    exit 1
fi

#
#  Check if reboot is required
#
# /usr/lib/update-notifier/update-motd-reboot-required

display_time_elapsed "Mapk"
