#!/bin/sh

#
# Simulating the restore-ish output style
#
function msg_2() {
    local msg=$1

    echo "=== $msg ==="
}

function msg_3() {
    local msg=$1

    echo "--- $msg ---"
}

cd_to() {
    #
    # All this just to get rid of shellcheck complaining abot a cd
    # should always check for failure, thats a bit nitpicky if you
    # ask me...
    #
    dest=$1
    [ "$dest" = "" ] && dest="$HOME"

    if ! cd "$dest"; then
	echo "Failed to cd to $dest"
	exit 1
    fi
}


msg_2 "Softlinking ~/cloud"
cd_to 
ln -sf /iCloud/cloud .
echo

