#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  Copyright (c) 2023-2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Intended to be used for inittab tasks, in order to skip tasks if
#  recovery mode is selected
#

log_it() {
    echo "$(date +"%Y-%m-%d %H:%M:%S") $1" >>"$f_recovery_log_file"
}

f_recovery_mode=/etc/opt/ift/recovery-mode
f_recovery_log_file=/var/log/recovery-mode.log

[ -f "$f_recovery_mode" ] && {
    log_it "R-check detected recovery mode - skipped: ${*}"
    exit 0
}
# For debugging, also list what inittab tasks will run
# log_it "R-check will run: ${*}"

# run the intended task
"$@"
