#!/bin/sh

#
# Simulating the spd output style, since this is not sourced
#
msg_2() {
    echo "=== $1 ==="
}

msg_3() {
    echo "--- $1 ---"
}


msg_2 "Softlinking ~/cloud"
dest=$1
[ "$dest" = "" ] && dest="$HOME"

if ! cd "$dest"; then
    echo "Failed to cd to $dest"
    exit 1
fi

ln -sf /iCloud/cloud .
echo
