#!/bin/sh
# ^^^ just a helper for editors
#
#   sourced, so variables / functions can be used.
#
#   This is just a sample, comment out or replace to fit your needs.
#


#
#   Verifies SPD_UNAME has been set, use if the username is needed in the tasks below
#
[ -z "$SPD_UNAME" ] && error_msg "This additional-restore-tasks can not run without a SPD_UNAME set!" 1


#
#   Adding some stuff to /usr/local/bin
#
msg_2 "Adding to /usr/local/bin"
msg_3 "path_modify.sh"
ln -sf /usr/local/shell_envs/scripts/path_modify.sh /usr/local/bin
echo


#
#   Run additional-as-$SPD_UNAME script, if found
#
my_additional_stuff=$DEPLOY_PATH/custom/additional-as-$SPD_UNAME
if ! test -f "$my_additional_stuff" ; then
    error_msg "Not found: $my_additional_stuff"
elif test -x "$my_additional_stuff" ; then
    msg_1 "user-based extra script"
    echo "Runnig:    $my_additional_stuff"
    echo
    /bin/su -c "$my_additional_stuff" - "$SPD_UNAME"
    echo "Completed: $my_additional_stuff"
else
    error_msg "$my_additional_stuff is not a run-able script!"
fi
